[package]
name = "calculator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19"
web-sys = { version = "0.3.56", features = ["HtmlInputElement"] }
wasm-bindgen = "0.2.79"
gloo = "0.6.1"